export const QUERY_KEYS = {
  MENU: "MENU",
  CATEGORIES: "CATEGORIES",
  ADMIN_DASHBOARD: "ADMIN_DASHBOARD",
  STAFF: "STAFF",
  KTICHEN_LIVE: "KITCHEN_LIVE",
  WAITER_LIVE: "WAITER_LIVE",
  TABLE_LIVE: "TABLE_LIVE",
  SESSION_SUBORDERS: "SESSION_SUBORDERS",
  UNSETTLED_ORDERS:"UNSETTLED_ORDERS"
}
